version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=123456qq789
      - JWT_SECRET=your_jwt_secret
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456qq789"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:








